import 'dart:html';
import 'package:json_to_dart/json_to_dart.dart';
import 'package:json_ast/json_ast.dart';
import 'package:json_to_dart/syntax.dart';
import 'package:json_to_dart/helpers.dart';
import './json.dart';
import './ace.dart';
import './highlight.dart';

typedef ACEEditorAnnotation? _annotationMapper(Warning w);

void main() {
  final ButtonElement convertButton =
      document.querySelector('button[type="submit"]') as ButtonElement;
  final highlightedDartCode = document.querySelector('pre code.dart');
  final CheckboxInputElement usePrivateFieldsCheckbox =
      document.querySelector('#private-fields') as CheckboxInputElement;
  final CheckboxInputElement generateToJsonCheckbox =
      document.querySelector('#generate-tojson') as CheckboxInputElement;
  final ButtonElement copyClipboardButton =
      document.querySelector('#copy-clipboard') as ButtonElement;
  final TextAreaElement hiddenElement =
      document.querySelector('#hidden-dart') as TextAreaElement;
  final InputElement dartClassNameInput =
      document.querySelector('#dartClassName') as InputElement;
  final Element? boldElement = document.querySelector('#invalid-dart');
  final Element? jsonEditor = document.querySelector('#jsonEditor');
  final DivElement excludeFieldsContainer =
      document.querySelector('#exclude-fields-container') as DivElement;
  final DivElement excludeFieldsList =
      document.querySelector('#exclude-fields-list') as DivElement;

  final Set<String> excludedFields = {};
  Set<String> lastKeys = {};

  final editor = ace.edit(jsonEditor!);
  editor.setTheme('ace/theme/github');
  editor.getSession().setMode("ace/mode/json");
  editor.getSession().setOption("useWorker", false);

  void _extractKeys(dynamic obj, Set<String> keys) {
    if (obj is Map) {
      for (var key in obj.keys) {
        if (key is String) {
          keys.add(key);
          _extractKeys(obj[key], keys);
        }
      }
    } else if (obj is List) {
      for (var item in obj) {
        _extractKeys(item, keys);
      }
    }
  }

  void doGenerate([bool jsonChanged = false]) {
    var dartClassName = dartClassNameInput.value;
    if (dartClassName!.trim() == '') {
      dartClassName = 'Autogenerated';
    }
    var syntaxError = false;
    var invalidDart = false;
    var json = editor.getValue();
    dynamic obj;
    try {
      obj = jsonParse(json);
    } catch (e) {
      syntaxError = true;
      if (jsonChanged) {
        window.alert('The json provider has syntax errors');
      }
    }
    if (!syntaxError) {
      if (jsonChanged) {
        json = jsonStringify(obj, null, 4);
        editor.setValue(json);
      }
      editor.getSession().clearAnnotations();

      final Set<String> currentKeys = {};
      _extractKeys(obj, currentKeys);

      if (jsonChanged || !currentKeys.containsAll(lastKeys) || !lastKeys.containsAll(currentKeys)) {
        excludedFields.retainAll(currentKeys);
        lastKeys = currentKeys;

        excludeFieldsList.children.clear();
        if (currentKeys.isNotEmpty) {
          excludeFieldsContainer.style.display = 'block';
          for (var key in currentKeys) {
            final label = LabelElement()
              ..style.display = 'block'
              ..style.margin = '2px 0';
            final checkbox = CheckboxInputElement()
              ..checked = !excludedFields.contains(key)
              ..style.marginRight = '8px';
            checkbox.onChange.listen((_) {
              if (checkbox.checked!) {
                excludedFields.remove(key);
              } else {
                excludedFields.add(key);
              }
              doGenerate(false);
            });
            label.append(checkbox);
            label.appendText(key);
            excludeFieldsList.append(label);
          }
        } else {
          excludeFieldsContainer.style.display = 'none';
        }
      }

      final modelGenerator = new ModelGenerator.withOptions(
          dartClassName,
          privateFields: usePrivateFieldsCheckbox.checked!,
          generateToJson: generateToJsonCheckbox.checked!,
          ignoredFields: excludedFields.toList());
      DartCode? dartCode;
      try {
        dartCode = modelGenerator.generateDartClasses(json);
        boldElement!.style.display = 'none';
      } catch (e) {
        invalidDart = true;
      }
      if (invalidDart) {
        try {
          dartCode = modelGenerator.generateUnsafeDart(json);
        } catch (e) {
          if (jsonChanged) {
            window.alert(
                'Cannot generate dart code. Please check the project caveats.');
          }
          hiddenElement.value = '';
          highlightedDartCode!.text = '';
          copyClipboardButton.attributes
              .putIfAbsent('disabled', () => 'disabled');
          print(e);
          return;
        }
        boldElement!.style.display = 'block';
      }
      if (dartCode!.warnings != null) {
        try {
          final annotationMapper = buildAnnotationMapper(
              parse(json, Settings(source: 'input.json')));
          final annotations = dartCode.warnings
              .map(annotationMapper)
              .where((a) => a != null)
              .toList() as List<ACEEditorAnnotation>;
          editor.getSession().setAnnotations(annotations);
        } catch (e) {
          print('Error attempting to set annotations: $e');
        }
      }
      hiddenElement.value = dartCode.code;
      highlightedDartCode!.text = dartCode.code;
      copyClipboardButton.attributes.remove('disabled');
      hljs.highlightBlock(highlightedDartCode);
    } else {
      hiddenElement.value = '';
      highlightedDartCode!.text = '';
      copyClipboardButton.attributes.putIfAbsent('disabled', () => 'disabled');
      excludeFieldsContainer.style.display = 'none';
    }
  }

  copyClipboardButton.onClick.listen((MouseEvent event) {
    event.preventDefault();
    event.stopPropagation();
    if (!copyClipboardButton.disabled) {
      hiddenElement.select();
      document.execCommand("Copy");
    }
  });

  convertButton.onClick.listen((MouseEvent event) {
    event.preventDefault();
    event.stopPropagation();
    doGenerate(true);
  });

  usePrivateFieldsCheckbox.onChange.listen((_) => doGenerate(false));
  generateToJsonCheckbox.onChange.listen((_) => doGenerate(false));
}

_annotationMapper buildAnnotationMapper(Node root) {
  return (Warning w) => annotationForWarning(root, w);
}

final _arrayElementRegExp = new RegExp(r"\[([0-9]+)\]");

ACEEditorAnnotation? annotationForWarning(Node root, Warning w) {
  Node? node = root;
  final paths = w.path.split('/');
  paths.where((p) => p.trim() != '').forEach((p) {
    if (_arrayElementRegExp.hasMatch(p)) {
      var splittedPath = p.split('[');
      // navigate property
      node = navigateNode(node, splittedPath[0]);
      splittedPath = splittedPath[1].split(']');
      // navigate index
      node = navigateNode(node, splittedPath[0]);
    } else {
      node = navigateNode(node, p);
    }
  });
  ACEEditorAnnotation annotation;
  print('node: ${node}');
  if (node is LiteralNode) {
    annotation = ACEEditorAnnotation();
    print('new annotation at line ${node!.loc!.start.line}');
    print('new annotation at column ${node!.loc!.start.column}');
    annotation.row = node!.loc!.start.line - 1;
    annotation.column = node!.loc!.start.column - 1;
    annotation.text = w.warning;
    annotation.type = 'error';
    return annotation;
  }
  return null;
}
